"""
Tier 2 — Run the Function App's handler logic on a plain HTTP server.

Imports `function_app.call_agent` and the SSE-result helpers, so this exercises
the production Cortex Agents REST code path minus the Azure Functions runtime.

Reads env vars from azure_deploy/function/local.settings.json (generated by
make_local_settings.py) before importing function_app.

Usage:
    python local_test_server.py
    # GET  http://localhost:7071/api/health
    # POST http://localhost:7071/api/chat   with {"question": "..."}
    # POST http://localhost:7071/api/summary  (no-op, returns {"summary": ""})
"""

import json
import logging
import os
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT          = Path(__file__).resolve().parent.parent
FUNCTION_DIR  = ROOT / "azure_deploy" / "function"
SETTINGS_PATH = FUNCTION_DIR / "local.settings.json"

PORT = 7071

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("voc-local")

# ─── Load env vars before importing function_app ─────────────────────────────
if not SETTINGS_PATH.exists():
    sys.exit(f"Missing {SETTINGS_PATH}. Run make_local_settings.py first.")

settings = json.loads(SETTINGS_PATH.read_text())
for k, v in settings.get("Values", {}).items():
    os.environ.setdefault(k, v)

# Make function_app importable
sys.path.insert(0, str(FUNCTION_DIR))
import function_app as fa  # noqa: E402


# ─── HTTP server ─────────────────────────────────────────────────────────────
class Handler(BaseHTTPRequestHandler):

    def log_message(self, fmt, *args):
        log.info("%s - %s", self.address_string(), fmt % args)

    def _cors(self):
        self.send_header("Access-Control-Allow-Origin",  "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def _json(self, payload, status=200):
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self._cors()
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.end_headers()

    def do_GET(self):
        if self.path == "/api/health":
            self._json({"status": "ok", "account": fa._account_locator()})
            return
        self._json({"error": "not found"}, 404)

    def do_POST(self):
        if self.path == "/api/summary":
            # No-op for backwards compat (new pipeline returns summary in /api/chat)
            self._json({"summary": ""})
            return
        if self.path != "/api/chat":
            self._json({"error": "not found"}, 404)
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            body   = json.loads(self.rfile.read(length))
        except (ValueError, json.JSONDecodeError):
            self._json({"error": "invalid JSON body"}, 400)
            return

        question = (body.get("question") or "").strip()
        history  = body.get("history") or []
        if not question:
            self._json({"error": "question is required"}, 400)
            return

        accept = (self.headers.get("Accept") or "").lower()
        if "text/event-stream" in accept:
            self._stream_chat(question, history)
        else:
            self._json_chat(question, history)

    def _stream_chat(self, question, history):
        """Stream upstream SSE through to the browser, then emit a `final` event
        with the aggregated payload. Mirrors function_app.stream_chat()."""
        self.send_response(200)
        self._cors()
        self.send_header("Content-Type",     "text/event-stream")
        self.send_header("Cache-Control",    "no-cache")
        self.send_header("X-Accel-Buffering", "no")
        self.end_headers()

        try:
            for chunk in fa.stream_chat(question, history):
                self.wfile.write(chunk)
                self.wfile.flush()  # critical for live streaming over BaseHTTPServer
        except (BrokenPipeError, ConnectionResetError):
            log.info("client disconnected mid-stream")
        except Exception:
            log.exception("stream handler failed")

    def _json_chat(self, question, history):
        try:
            result = fa.call_agent(question, history)
        except Exception as e:
            log.exception("agent:run call failed")
            self._json({"error": str(e)[:500]}, 500)
            return

        if result.error:
            log.warning("agent:run returned error: %s", result.error)
            self._json({"error": result.error[:500]}, 502)
            return

        self._json(fa._build_aggregate_payload(result, question))


def main():
    log.info("Loaded env from %s", SETTINGS_PATH)
    log.info("Snowflake account locator: %s", fa._account_locator())
    log.info("VOC local function server  http://localhost:%d", PORT)
    log.info("  GET  /api/health")
    log.info("  POST /api/chat   {\"question\": \"...\"}")
    log.info("Ctrl+C to stop.")
    with ThreadingHTTPServer(("127.0.0.1", PORT), Handler) as httpd:
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            log.info("Stopped.")


if __name__ == "__main__":
    main()
