"""
Tier 2 — Run the Function App's handler logic on a plain HTTP server.

Imports `function_app.call_agent` and the SSE-result helpers, so this exercises
the production Cortex Agents REST code path minus the Azure Functions runtime.

Reads env vars from azure_deploy/function/local.settings.json (generated by
make_local_settings.py) before importing function_app.

Usage:
    python local_test_server.py
    # GET  http://localhost:7071/api/health
    # POST http://localhost:7071/api/chat   with {"question": "..."}
    # POST http://localhost:7071/api/summary  (no-op, returns {"summary": ""})
"""

import json
import logging
import os
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT          = Path(__file__).resolve().parent.parent
FUNCTION_DIR  = ROOT / "azure_deploy" / "function"
SETTINGS_PATH = FUNCTION_DIR / "local.settings.json"

PORT = 7071

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("voc-local")

# ─── Load env vars before importing function_app ─────────────────────────────
if not SETTINGS_PATH.exists():
    sys.exit(f"Missing {SETTINGS_PATH}. Run make_local_settings.py first.")

settings = json.loads(SETTINGS_PATH.read_text())
for k, v in settings.get("Values", {}).items():
    os.environ.setdefault(k, v)

# Make function_app importable
sys.path.insert(0, str(FUNCTION_DIR))
import function_app as fa  # noqa: E402


# ─── HTTP server ─────────────────────────────────────────────────────────────
class Handler(BaseHTTPRequestHandler):

    def log_message(self, fmt, *args):
        log.info("%s - %s", self.address_string(), fmt % args)

    def _cors(self):
        self.send_header("Access-Control-Allow-Origin",  "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def _json(self, payload, status=200):
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self._cors()
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.end_headers()

    def do_GET(self):
        if self.path == "/api/health":
            self._json({"status": "ok", "account": fa._account_locator()})
            return
        self._json({"error": "not found"}, 404)

    def do_POST(self):
        if self.path == "/api/summary":
            # New pipeline: summary is already in /api/chat's response. Return empty
            # for backwards compat with frontends that still POST here.
            self._json({"summary": ""})
            return
        if self.path != "/api/chat":
            self._json({"error": "not found"}, 404)
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            body   = json.loads(self.rfile.read(length))
        except (ValueError, json.JSONDecodeError):
            self._json({"error": "invalid JSON body"}, 400)
            return

        question = (body.get("question") or "").strip()
        history  = body.get("history") or []
        if not question:
            self._json({"error": "question is required"}, 400)
            return

        try:
            result = fa.call_agent(question, history)
        except Exception as e:
            log.exception("agent:run call failed")
            self._json({"error": str(e)[:500]}, 500)
            return

        if result.error:
            log.warning("agent:run returned error: %s", result.error)
            self._json({"error": result.error[:500]}, 502)
            return

        last_tool_use = result.last_sql_tool_use
        last_sql      = ((last_tool_use or {}).get("input") or {}).get("sql") if last_tool_use else None
        last_tool_res = result.last_sql_result
        data          = None
        if last_tool_res:
            payload = (last_tool_res.get("content") or [{}])[0]
            rs      = (payload.get("json") or {}).get("result_set") or {}
            data    = {
                "columns": fa._extract_columns(rs, last_sql or ""),
                "rows":    fa._extract_rows(rs),
            }

        data_kind  = fa._data_kind(data) if data else "metric"
        sql_failed = data is None and last_sql is not None

        self._json({
            "type":           "agent",
            "summary":        result.final_text,
            "interpretation": result.final_text,    # bubble reads this on first paint
            "details":        result.thinking,
            "sql":            last_sql,
            "data":           data,
            "data_kind":      data_kind,
            "suggestions":    result.suggestions[:3],
            "warnings":       [],
            "sql_failed":     sql_failed,
            "history_update": [
                {"role": "user",      "content": [{"type": "text", "text": question}]},
                {"role": "assistant", "content": [{"type": "text", "text": result.final_text}]},
            ],
            "agent_meta": {
                "status_messages": result.status_messages,
                "tool_use_count":  len(result.tool_uses),
            },
        })


def main():
    log.info("Loaded env from %s", SETTINGS_PATH)
    log.info("Snowflake account locator: %s", fa._account_locator())
    log.info("VOC local function server  http://localhost:%d", PORT)
    log.info("  GET  /api/health")
    log.info("  POST /api/chat   {\"question\": \"...\"}")
    log.info("Ctrl+C to stop.")
    with ThreadingHTTPServer(("127.0.0.1", PORT), Handler) as httpd:
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            log.info("Stopped.")


if __name__ == "__main__":
    main()
